Your commit message

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -39,10 +39,18 @@ jobs:
           bundle init
           echo 'gem "fastlane"' >> Gemfile
           bundle install
-          mkdir -p fastlane
-          echo "${{ secrets.APP_STORE_CONNECT_API_PRIVATE_KEY }}" | base64 --decode > fastlane/AuthKey.p8
-          ls -l fastlane/AuthKey.p8  # Debugging: Check if file exists
+
+      - name: Verify AuthKey.p8 File
+        run: |
+          if [ ! -f "ios/fastlane/AuthKey.p8" ]; then
+            echo "❌ AuthKey.p8 is missing in ios/fastlane!"
+            exit 1
+          fi
+          echo "✅ AuthKey.p8 found."
           echo "APP_STORE_CONNECT_API_PRIVATE_KEY_PATH=$GITHUB_WORKSPACE/ios/fastlane/AuthKey.p8" >> $GITHUB_ENV
+
+      - name: Debug Fastlane Files
+        run: ls -la ios/fastlane
 
       - name: Configure Fastlane
         run: |
@@ -86,7 +94,7 @@ jobs:
         env:
           APP_STORE_CONNECT_API_KEY_ID: ${{ secrets.APP_STORE_CONNECT_API_KEY_ID }}
           APP_STORE_CONNECT_ISSUER_ID: ${{ secrets.APP_STORE_CONNECT_ISSUER_ID }}
-          APP_STORE_CONNECT_API_PRIVATE_KEY_PATH: ${{ secrets.APP_STORE_CONNECT_API_PRIVATE_KEY_PATH }}
+          APP_STORE_CONNECT_API_PRIVATE_KEY_PATH: ${{ env.APP_STORE_CONNECT_API_PRIVATE_KEY_PATH }}
           FASTLANE_OPT_OUT_USAGE: true
 
       - name: Complete job
